serverFiles:
  alerting_rules.yml:
    groups:
      - name: appgroup
        rules:
        - alert: DeploymentReplicas
          expr: kube_deployment_status_replicas_available{deployment="st2dce-tahj"} < 2
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Deployment st2dce-tahj has less than 2 replicas available"

alertmanager:
  config:

    enabled: true
    global: 
      smtp_smarthost: 'smtp.office365.com:587'
      smtp_from: 'thibault.henrion@efrei.net'
      smtp_auth_username: 'thibault.henrion@efrei.net'
      smtp_auth_password: 'password'


    templates:
      - '/etc/alertmanager/*.tmpl'
      - '/etc/alertmanager/template/*.tmpl'

    receivers:
      - name: email-notifications
        email_configs:
          - to: 'thibault.henrion1@gmail.com'
            send_resolved: true
            headers:
              subject: 'Alert from group ST2DCE-TAHJ : less than 2 replicas for service'

    route:
      group_wait: 10s
      group_interval: 5m
      receiver: email-notifications
      repeat_interval: 3h
